package com.workflow.common.constant.notification;

public enum NotificationType {
    FORCE_LOGOUT,
    VISIT_LOG_ADDED,
    STEP_STATUS_CHANGED,
    STEP_COMPLETED,
    STEP_COMMENT_ADDED,
    STEP_ATTACHMENT_ADDED,
    STEP_COMMENT_UPDATED,
    STEP_ATTACHMENT_UPDATED,
    WORKER_ASSIGNED,
    ASSET_SLA_BREACHED,
    STEP_SLA_BREACHED
}