#!/usr/bin/env bash
set -euo pipefail

REGION="eu-central-1"
ENV_NAME="dev"
APP_DIR="/home/ubuntu/app"

echo "[setup-env] Pulling secrets and parameters from AWS..."

# ── Secrets Manager ──
DB_SECRET=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "/workflow/$ENV_NAME/database" --query SecretString --output text)
DB_HOST=$(echo "$DB_SECRET"  | jq -r '.host')
DB_PORT=$(echo "$DB_SECRET"  | jq -r '.port // 3306')
DB_NAME=$(echo "$DB_SECRET"  | jq -r '.dbname')
DB_USER=$(echo "$DB_SECRET"  | jq -r '.username')
DB_PASS=$(echo "$DB_SECRET"  | jq -r '.password')

JWT_SECRET=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "/workflow/$ENV_NAME/jwt" --query SecretString --output text)

MAIL_SECRET=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "/workflow/$ENV_NAME/mail" --query SecretString --output text)
MAIL_HOST=$(echo "$MAIL_SECRET"      | jq -r '.host')
MAIL_PORT=$(echo "$MAIL_SECRET"      | jq -r '.port')
MAIL_USERNAME=$(echo "$MAIL_SECRET"  | jq -r '.username')
MAIL_PASSWORD=$(echo "$MAIL_SECRET"  | jq -r '.password')
MAIL_FROM=$(echo "$MAIL_SECRET"      | jq -r '.from')
MAIL_FROM_NAME=$(echo "$MAIL_SECRET" | jq -r '.fromName')

# ── SSM Parameter Store ──
get_param() { aws ssm get-parameter --region "$REGION" --name "$1" --query Parameter.Value --output text; }
CORS_ORIGINS=$(get_param "/workflow/$ENV_NAME/cors-allowed-origins")
FRONTEND_URL=$(get_param "/workflow/$ENV_NAME/frontend-url")
S3_BUCKET=$(get_param "/workflow/$ENV_NAME/s3-bucket-name")
S3_REGION=$(get_param "/workflow/$ENV_NAME/s3-region")
APP_DOMAIN=$(get_param "/workflow/$ENV_NAME/app-domain")
GOOGLE_CLIENT_ID=$(get_param "/workflow/$ENV_NAME/google-client-id")

# ── Write .env.dev ──
{
  echo "# Auto-generated by setup-env.sh — do not edit manually"
  echo "# Re-run: sudo -u ubuntu /home/ubuntu/app/setup-env.sh"
  echo ""
  echo "# Database"
  echo "DB_URL=$DB_HOST"
  echo "DB_PORT=$DB_PORT"
  echo "DB_NAME=$DB_NAME"
  echo "DB_USERNAME=$DB_USER"
  echo "DB_PASSWORD=$DB_PASS"
  echo ""
  echo "# JWT"
  echo "JWT_SECRET=$JWT_SECRET"
  echo ""
  echo "# Mail (AWS SES)"
  echo "MAIL_HOST=$MAIL_HOST"
  echo "MAIL_PORT=$MAIL_PORT"
  echo "MAIL_USERNAME=$MAIL_USERNAME"
  echo "MAIL_PASSWORD=$MAIL_PASSWORD"
  echo "MAIL_FROM=$MAIL_FROM"
  echo "MAIL_FROM_NAME=$MAIL_FROM_NAME"
  echo ""
  echo "# CORS"
  echo "CORS_ALLOWED_ORIGINS=$CORS_ORIGINS"
  echo ""
  echo "# Frontend"
  echo "FRONTEND_URL=$FRONTEND_URL"
  echo ""
  echo "# S3 — EC2 instance role is used; leave access keys empty"
  echo "AWS_ACCESS_KEY_ID="
  echo "AWS_SECRET_ACCESS_KEY="
  echo "AWS_S3_REGION=$S3_REGION"
  echo "AWS_S3_BUCKET_NAME=$S3_BUCKET"
  echo ""
  echo "# Google OAuth"
  echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
  echo ""
  echo "# Spring"
  echo "SPRING_PROFILES_ACTIVE=dev"
  echo "HIBERNATE_DDL_AUTO=none"
  echo "FLYWAY_ENABLED=true"
  echo "FLYWAY_CLEAN_DISABLED=true"
  echo ""
  echo "# Nginx"
  echo "NGINX_DOMAIN=$APP_DOMAIN"
  echo ""
  echo "# Set by CI/CD before docker-compose up"
  echo "ECR_IMAGE_URI="
} > "$APP_DIR/.env.dev"
chmod 600 "$APP_DIR/.env.dev"
chown ubuntu:ubuntu "$APP_DIR/.env.dev"
echo "[setup-env] Done — .env.dev written to $APP_DIR/.env.dev"
